### ISSUE TITLE
Failing to compile on Travis with Node 4.2.1

### ISSUE THREAD

**Issue by wbyoung** [bnoordhuis/node-unix-dgram#30]
In a project that I'm working on, one of our dependencies uses `node-unix-dgram` and I'm getting [errors when trying to install](https://gist.github.com/wbyoung/60b07d2929b56e5a75a9) using Node 4.2.1 and Node 5.

I was wondering if you might have an idea of what the issue is here or maybe could point me in the right direction to get it resolved?

**Comment by santigimeno** [comment]
I read somewhere that Travis hasn't upgraded their infrastructure yet to support Ubuntu 14-04 that contains a valid gcc to build binary addons in latest nodejs versions.

**Comment by wbyoung** [comment]
Thanks for the tip. Found Travis issue travis-ci/travis-ci#4771, and the following worked for me:

```yaml
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
env:
    global:
        - CXX=g++-4.8
```
